name: Build Everything, make artifact

on:
  workflow_dispatch:
  workflow_call:

jobs:
  # Single deploy job since we're just deploying
  build-rco3-installer:
    runs-on: ubuntu-latest
    environment:
      name: "Artifact rco3installer"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'RCO3Installer/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd RCO3Installer
          pnpm install
      - name: Build
        run: |
          cd RCO3Installer
          pnpm run build
      - name: Package
        run: |
          cd RCO3Installer
          pnpm run package
      - name: Make Artifact Dir
        run: |
          mkdir artifact
          mv RCO3Installer/dist/ artifact/installer-js
          mv RCO3Installer/bin/ artifact/installer-bin
          cp artifact/installer-bin/rco3installer-win.exe artifact/RCO2Installer.exe # upgrade from v2 to v3 installer
          echo $(sha512sum artifact/installer-js/index.js | cut -d ' ' -f 1) > artifact/installer-js/index.js.hash
      - name: Upload RCO3 Installers
        uses: actions/upload-artifact@v3
        with:
          name: rco3installer
          path: artifact
  build-rco3-site:
    runs-on: ubuntu-latest
    environment:
      name: "Artifact rco3site"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'rco-site/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd rco-site
          pnpm install
      - name: Build Site
        run: |
          cd rco-site
          pnpm build
      - name: Upload RCO3 Site
        uses: actions/upload-artifact@v3
        with:
          name: rco3site
          path: rco-site/build
  build-librco3:
    runs-on: ubuntu-latest
    environment:
      name: "Artifacts librco3-dist and librco3-docs"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'LibRCO3/pnpm-lock.yaml'
      - name: Install dependencies
        run: |
          cd LibRCO3
          pnpm install
      - name: Build Site
        run: |
          cd LibRCO3
          pnpm build
      - name: Build Docs
        run: |
          cd LibRCO3
          pnpm build:docs
      - name: Upload RCO3 Library
        uses: actions/upload-artifact@v3
        with:
          name: librco3-dist
          path: LibRCO3/dist
      - name: Upload RCO3 Docs
        uses: actions/upload-artifact@v3
        with:
          name: librco3-docs
          path: LibRCO3/docs
  build-rco3:
    needs: [build-librco3]
    runs-on: ubuntu-latest
    environment:
      name: "Artifact rco3"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download LibRCO3
        uses: actions/download-artifact@v3
        with:
          name: librco3-dist
          path: LibRCO3/dist
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'RCO3/pnpm-lock.yaml'
      - name: Install dependencies of LibRCO3
        run: |
          cd LibRCO3
          pnpm i
      - name: Install dependencies
        run: |
          cd RCO3
          pnpm i
      - name: Build
        run: |
          cd RCO3
          pnpm build
      - name: Zip
        run: |
          cd RCO3
          mv dist RCO-JS
          zip RCO.zip RCO-JS/**/* RCO-JS/*
          cd ..
          mv RCO3/RCO.zip ./RCO.zip
      - name: Deploy RCO3
        uses: actions/upload-artifact@v3
        with:
          name: rco3
          path: RCO.zip
  build-rco3-launcher:
    environment:
      name: "Artifact rco3launcher-${{matrix.os}}"
    # use matrix for os
    runs-on: ${{matrix.os == 'linux' && 'ubuntu-latest' || matrix.os == 'macos-intel' && 'macos-latest' || matrix.os == 'macos-apple' && 'macos-latest' || matrix.os == 'windows' && 'windows-latest'}}
    strategy:
      matrix:
        os: [linux, macos-intel, macos-apple, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache RCO3Launcher -> Target
        id: rust-launcher-cache
        uses: actions/cache@v3
        with:
          path: RCO3Launcher/target
          key: ${{ matrix.os }}-rco-launcher${{matrix.os=='windows'&&hashFiles('RCO3Launcher/src')||''}}-rust-target-cache-${{ hashFiles('RCO3Launcher/Cargo.lock') }}
      - name: Cache Home -> Cargo
        id: rust-launcher-homecargo-cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ matrix.os }}-rco-launcher-rust-home-cargo-cache-${{ hashFiles('RCO3Launcher/Cargo.lock') }}
      - name: Download last build
        if: steps.rust-launcher-cache.outputs.cache-hit == 'true' && matrix.os=='windows'
        run: |
          cd RCO3Launcher
          curl -o rco3launcher-win32-x86_64.exe https://roblox-client-optimizer.simulhost.com/launcher/rco3launcher-win32-x86_64.exe
      - name: Build
        if: steps.rust-launcher-cache.outputs.cache-hit != 'true' || matrix.os!='windows'
        run: |
          cd RCO3Launcher
          rustup target add ${{ matrix.os == 'linux' && 'x86_64-unknown-linux-gnu' || matrix.os == 'macos-intel' && 'x86_64-apple-darwin' || matrix.os == 'macos-apple' && 'aarch64-apple-darwin' || matrix.os == 'windows' && 'x86_64-pc-windows-msvc' }}
          cargo build --release --target ${{ matrix.os == 'linux' && 'x86_64-unknown-linux-gnu' || matrix.os == 'macos-intel' && 'x86_64-apple-darwin' || matrix.os == 'macos-apple' && 'aarch64-apple-darwin' || matrix.os == 'windows' && 'x86_64-pc-windows-msvc' }}
          mv target/${{ matrix.os == 'linux' && 'x86_64-unknown-linux-gnu' || matrix.os == 'macos-intel' && 'x86_64-apple-darwin' || matrix.os == 'macos-apple' && 'aarch64-apple-darwin' || matrix.os == 'windows' && 'x86_64-pc-windows-msvc' }}/release/rco3launcher${{ matrix.os == 'windows' && '.exe' || '' }} ./rco3launcher-${{ matrix.os == 'linux' && 'linux-x86_64' || matrix.os == 'macos-intel' && 'darwin-x86_64' || matrix.os == 'macos-apple' && 'darwin-arm64' || matrix.os == 'windows' && 'win32-x86_64.exe' }}
      - name: Install pnpm (Windows)
        uses: pnpm/action-setup@v2
        if: matrix.os == 'windows'
        with:
          version: 'latest'
      - name: Install Node.js (Windows)
        if: matrix.os == 'windows'
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run Metadata Tool (Windows)
        if: matrix.os == 'windows'
        run: |
          cd RCO3Launcher/metadata
          pnpm i --no-frozen-lockfile
          cd ..
          node metadata/index.js rco3launcher-win32-x86_64.exe
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rco3launcher-${{matrix.os}}
          path: RCO3Launcher/rco3launcher-*
  build-rbx2appdata:
    environment:
      name: "Artifact rbx2appdata-${{matrix.os}}"
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache rbx2appdata -> Target
        id: rust-rbx2appdata-cache
        uses: actions/cache@v3
        with:
          path: RBX2Appdata/target
          key: ${{ matrix.os }}-${{hashFiles('RBX2Appdata/src')}}-rust-target-cache-${{ hashFiles('RBX2Appdata/Cargo.lock') }}
      - name: Cache Home -> Cargo
        id: rust-rbx2appdata-homecargo-cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ matrix.os }}-rco-launcher-rust-home-cargo-cache-${{ hashFiles('RBX2Appdata/Cargo.lock') }}
      - name: Download last build
        if: steps.rust-rbx2appdata-cache.outputs.cache-hit == 'true'
        run: |
          cd RBX2Appdata
          curl -o rbx2appdata.exe https://roblox-client-optimizer.simulhost.com/rbx2appdata.exe
      - name: Build
        if: steps.rust-rbx2appdata-cache.outputs.cache-hit != 'true'
        run: |
          cd RBX2Appdata
          cargo build --release
          mv target/release/rbx2appdata.exe ./rbx2appdata.exe
      - name: Install pnpm (Windows)
        uses: pnpm/action-setup@v2
        if: matrix.os == 'windows'
        with:
          version: 'latest'
      - name: Install Node.js (Windows)
        if: matrix.os == 'windows'
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run Metadata Tool (Windows)
        if: matrix.os == 'windows'
        run: |
          cd RCO3Launcher/metadata
          pnpm i --no-frozen-lockfile
          cd ../../RBX2Appdata
          node ../RCO3Launcher/metadata/index.js rbx2appdata.exe icon.ico --rbx2ad
          pnpm i -g resedit-cli
          resedit rbx2appdata.exe rbx2appdata.exe --raw 24,1,@res/app.manifest
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rbx2appdata
          path: RBX2Appdata/rbx2appdata.exe
  upload-static:
    runs-on: ubuntu-latest
    environment:
      name: "Artifact assets"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create RCO ClientAppSettings Hash
        run: |
          echo $(sha512sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.sha512
          echo $(sha256sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.sha256
          echo $(md5sum assets/ClientAppSettings.json | cut -d ' ' -f 1) > assets/ClientAppSettings.json.md5
      - name: Deploy Static
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: assets
  merge-rco3-launcher:
    environment:
      name: "Artifact rco3launcher"
    runs-on: ubuntu-latest
    needs: [build-rco3-launcher]
    steps:
      - name: Install binutils
        run: |
          sudo apt-get update
          sudo apt-get install binutils
      - name: Download RCO3 Launcher Linux
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-linux
          path: launcher
      - name: Download RCO3 Launcher Windows
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-windows
          path: launcher
      - name: Download RCO3 Launcher Mac (Intel x86_64)
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-macos-intel
          path: launcher
      - name: Download RCO3 Launcher Mac (Apple Silicon)
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher-macos-apple
          path: launcher
      - name: Strip Windows
        run: |
          strip launcher/rco3launcher-linux-x86_64
      - name: Strip Linux
        run: |
          strip launcher/rco3launcher-win32-x86_64.exe
      - name: Hash
        run: |
          sha512sum launcher/rco3launcher-* > launcher/rco3launcher.sha512
      - name: Upload RCO3 Launcher
        uses: actions/upload-artifact@v3
        with:
          name: rco3launcher
          path: .
  merge-builds:
    runs-on: ubuntu-latest
    environment:
      name: "Artifact page"
    needs: [build-rco3-installer, build-rco3-site, build-rco3, build-librco3, upload-static, merge-rco3-launcher]
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Make Directories
        run:
          mkdir lib
      - name: Download RCO3 Site
        uses: actions/download-artifact@v3
        with:
          name: rco3site
          path: .
      - name: Download RCO3 Installer
        uses: actions/download-artifact@v3
        with:
          name: rco3installer
          path: .
      - name: Download RCO3
        uses: actions/download-artifact@v3
        with:
          name: rco3
          path: .
      - name: Download LibRCO3
        uses: actions/download-artifact@v3
        with:
          name: librco3-dist
          path: lib/dist
      - name: Download LibRCO3 Documentation
        uses: actions/download-artifact@v3
        with:
          name: librco3-docs
          path: lib/docs
      - name: Download RCO3Launcher
        uses: actions/download-artifact@v3
        with:
          name: rco3launcher
          path: .
      - name: Unzip
        run: |
          unzip -u RCO.zip
          rm RCO.zip
      - name: Download Assets
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: .
      - name: Create Important Hashes
        run: |
          sha512sum RCO.exe > RCOVersion
          sha512sum RCO2Installer.exe > RCO2Installer.hash
          sha512sum RCO-JS/* > RCO-JS/sha512sum.txt
          find . -type f -print0 | xargs -0 sha512sum | sha512sum > deployment.hash
      - name: Temp - Rename RCO-Legacy-Installer.exe to RCO2Installer.exe
        run: |
          find
          mv RCO2Installer.exe RCONextGen-Installer.exe
          mv RCO-Legacy-Installer.exe RCO2Installer.exe
      - name: Create Indexes where missing
        run: |
          pnpm create @3xpo/index build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: page
          path: .
